// ================================================================
// JUST GRIDDLIN' — Menu & Events Data
//
// This file is generated by the Owner Admin panel.
// DO NOT edit this file by hand — use admin.html instead.
//
// HOW TO PUBLISH CHANGES:
//  1. Open admin.html and make your changes
//  2. Click "Export to Site" — this file will download
//  3. Replace this file in your project folder with the new one
//  4. Go to netlify.com/drop and drag your whole project folder
//  5. Done — changes are live for everyone within 30 seconds
// ================================================================

var JG_MENU_ITEMS = [
  {cat:'Burgers',      name:"The Griddlin' Burger",  desc:'Fresh smash patty, special sauce, lettuce, tomato, grilled onion on a toasted bun.',     price:'$8',  img:'loaded burger.jpg',       soldOut:false},
  {cat:'Burgers',      name:'Steamer Burger',         desc:'Double smash patties straight off the flat top, melted cheese, caramelized onions.',     price:'$10', img:'buger with steam.jpg',     soldOut:false},
  {cat:'Hot Dogs',     name:'Loaded Dog',             desc:'All-beef hot dog piled high with your choice of toppings. Simple, perfect.',             price:'$6',  img:'loaded hotdog.jpg',        soldOut:false},
  {cat:'Breakfast',    name:'Breakfast Burrito',      desc:'Eggs, cheese, and your choice of meat wrapped fresh. Morning done the right way.',       price:'$7',  img:'breakfast bureot.jpg',     soldOut:false},
  {cat:'Loaded Faves', name:'Loaded Waffles',         desc:"Crispy waffles stacked with savory toppings. A Just Griddlin' signature.",               price:'$9',  img:'loaded waffols.jpg',       soldOut:false},
  {cat:'Loaded Faves', name:'Loaded Baked Potato',    desc:'Fully loaded baked potato with all the fixings. Comfort food done right.',               price:'$8',  img:'backed potato.jpg',        soldOut:false},
  {cat:'Snacks',       name:'Nachos',                 desc:'Crispy chips smothered in melted cheese, jalapeños, and all your favorite toppings.',   price:'$7',  img:'nacos.jpg',                soldOut:false},
  {cat:'Snacks',       name:'Walking Taco',           desc:"Doritos bag turned into a portable taco bowl. A fair food classic.",                    price:'$6',  img:'walking taco.jpg',         soldOut:false},
  {cat:'Snacks',       name:'Sloppy Joe',             desc:'Classic sloppy joe made our way. Messy in the best way possible.',                      price:'$7',  img:'sluppy joe.jpg',           soldOut:false}
];

var JG_EVENTS = [
  {date:'Check Facebook for Dates', name:'Eaton County Fair',  loc:'Eaton County Fairgrounds, MI',         img:'eaton county fair event.jpg'},
  {date:'Check Facebook for Dates', name:'Maple Festival',     loc:'Michigan',                             img:'maple fest even.jpg'},
  {date:'Check Facebook for Dates', name:'Speedway Events',    loc:'Local Speedway, MI',                   img:'speedway event.jpg'},
  {date:'Weekends & Events',        name:'Community Pop-Ups',  loc:'Follow us on FB for exact locations!', img:'event.jpg'}
];

// Founder photo — null means use the original founder josh.jpg file
var JG_FOUNDER_IMG = null;

// Custom gallery photos uploaded via admin — empty array means no extras
var JG_GALLERY_CUSTOM = [];
